version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: script_stop_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: script_before_install.sh
      timeout: 300
      runas: ec2-user
  Install:
    - location: script_install.sh
      timeout: 400
      runas: ec2-user
  ApplicationStart:
    - location: script_start_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: script_validate_application.sh
      timeout: 60
      runas: ec2-user