version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/application

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 646

hooks:
  ApplicationStop:
    - location: script/script_stop_server.sh
      timeout: 30
      runas: ec2-user
  Install:
    - location: script/script_install.sh
      timeout: 400
      runas: ec2-user
  ApplicationStart:
    - location: script/script_start_server.sh
      timeout: 300
      runas: ec2-user