version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/estudoapp.war estudoapp.war
artifacts:
  files:
    - estudoapp.war
    - appspec.yml
    - scripts/**
  discard-paths: yes