version: 0.2

phases:
  build:
    commands:
      - mvn clean install

artifacts:
  files:
    - target/estudoapp.jar
    - appspec.yml
    - scripts/start-process.sh
    - scripts/stop-process.sh
  discard-paths: yes