version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum update -y
      - yum install -y maven
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/**
  discard-paths: yes